### PR TITLE
Upgrade Jakarta Mail 2.1 dependencies

### PR DESCRIPTION
**Pull request by rtaugerbeck**
- jakarta.mail:jakarta.mail-api:2.1.2  (latest api version for Jakarta Mail API contained in Jakarta EE 10 https://jakarta.ee/release/10/
- org.eclipse.angus:angus-mail:2.0.2 (latest version for Jakarta Mail 2.1 implementation https://github.com/eclipse-ee4j/angus-mail)

### CODE REVIEW

**Review by davidmoten — APPROVED** [review]
Righto let's do it, thanks

**Comment by bbottema** [comment]
When are you releasing a version with this update? This library is currently blocking me from upgrading [Simple Java Mail](https://github.com/bbottema/simple-java-mail) to Angus Mail.

**Comment by davidmoten** [comment]
Shouldn't be a blocker I thought. Just exclude old and include new?

**Comment by bbottema** [comment]
That depends if you used classes from the implementation (now Angus), because the group nane and package name changed.

However, since it's a test dependency it turned out not to be an issue anyway. But still, I prefer not to have multiple java mailing frameworks on my classpath.

Do you have a release date in mind?

**Comment by davidmoten** [comment]
Ah this is merged already. Yep I'll build a release today.

**Comment by davidmoten** [comment]
7.0.1 on Maven Central now

**Comment by bbottema** [comment]
Thanks!

**Pull request merged**
