### PR TITLE
add BDAT support (CHUNKING)

### PR DESCRIPTION
**Pull request by davidmoten**
as per discussion #19, used [RFC 1830](https://tools.ietf.org/html/rfc1830) to add BDAT support.

### CODE REVIEW

**Comment by davidmoten** [comment]
@valenpo can you review please

**Comment by valenpo** [comment]
@davidmoten yup. Do it today.

**Comment by davidmoten** [comment]
@valenpo sorry I thought you meant you would review today. Are you saying ok by you?

**Comment by davidmoten** [comment]
This PR has been merged and released to Maven Central in 5.2.2

**Pull request merged**
