### PR TITLE
Added MessageContext knowledge to authentication

### PR DESCRIPTION
**Pull request by diegosalvi**
Pushed down MessageContext knowledge to Authentication mechanisms.
Knowning data from MessageContext is useful and sometimes needed to properly handle custom auth mechanism.

This patch breaks public interfaces. If not acceptable I can change it to support older interface and older custom implementations using default interface methods (but it will neel Java8 compatibility... BTW Java8 itself is EOL)

### CODE REVIEW

**Comment by davidmoten** [comment]
So an example might be ip based auth? What is your use case?

**Comment by davidmoten** [comment]
CI is failing, I think you have a compile error:

```
[ERROR] 
subethasmtp/src/test/java/org/subethamail/smtp/command/AuthTest.java:[5,43] ';' expected
```

**Comment by davidmoten** [comment]
BTW we already require Java 8 and I would like to conserve API compatibility at the moment so default methods would be good.

Java 8 is not EOL yet, just with Oracle free. AdoptOpenJDK 8 is still supported.

**Comment by davidmoten** [comment]
On second thoughts let's just release 5.x so don't use default methods.

**Comment by diegosalvi** [comment]
> CI is failing, I think you have a compile error:
> 
> ```
> [ERROR] 
> subethasmtp/src/test/java/org/subethamail/smtp/command/AuthTest.java:[5,43] ';' expected
> ```

Sorry for the missing ';', an unfortunate leftover while cleaning diffs (eclipse was adding too noise automatically :()

**Comment by diegosalvi** [comment]
> So an example might be ip based auth? What is your use case?

Actually we are using such patch to access remote ip and helo and use them during authentication process (expecially ip) alongside username and passwords.

**Pull request merged**
