### PR TITLE
add RejectException constructor with Throwable cause

### PR DESCRIPTION
**Pull request by SimoneDevkt**
Actually RejectException set the stacktrace to null, i want to add a constructor with Throwable par

### CODE REVIEW

**Comment by davidmoten** [comment]
Thanks but what is the point of this? If it did include a stack trace it would not be logged anywhere by subethasmtp. All subethasmtp cares about is a code and text to report via SMTP protocol using `RejectException.getErrorResponse()`.

**Comment by SimoneDevkt** [comment]
Is only for logging server side. I'm using vertx and i want to log the stacktrace when something throw an exception in my business logic. Now when i catch an error in onFailure callback i can't add this error in RejectException and i lost all the stacktrace.

**Comment by davidmoten** [comment]
So I still don't understand this. When you implement a MessageHandler for subethasmtp one of the implemented methods may throw a RejectException which you construct. Adding the causing exception will do nothing because subethasmtp (which is the thing calling your handler) does not log stack traces. So my only conclusion is you have written something that calls the MessageHandler method which is a bit weird to me. Can you show me?

**Comment by SimoneDevkt** [comment]
my handler is something like
`myVertxFuture.onFailure(error -> {
  System.out.println(error);
  throw error;
}`

myVertxFuture is a Future with an async task like a db query that can be throw an exception like SqlException
error is RejectException with my new constructor.
With my pr, println show stacktrace in stdout server side and client side print correctly only the single last RejectException.
Witout my pr, println show only the last RejectException and i can't understand if the problem was the query or the connection to db or something else

**Comment by davidmoten** [comment]
What does the interaction with subethsmtp look like? You are throwing a RejectException and catching it in your own code. The RejectException should be handled by subethasmtp, not you. If you are catching an exception early then use your own exception and map to RejectException only once ready to throw from the handler method

**Comment by SimoneDevkt** [comment]
> If you are catching an exception early then use your own exception and map to RejectException only once ready to throw from the handler method

I make this, i have created a class MyRejectException and when i catch error, i'm throwing `new RejectException(myRejectEx.getCode(), myRejectEx.getMessage()`, but i add a new class in my bl that can be in the subethsmtp.

I don't understand why add this new constructor is a problem, and why is better keep only constructors that adds null to the cause par

**Comment by davidmoten** [comment]
The main reason not to include a possible Throwable parameter in the constructor of this exception is because this functions as a message to users of the API that any Throwable passed would be ignored. Just continue using your custom exception and map at the last to the RejectException. If you have more information that you think might sway me then feel free to reopen the issue.

**Pull request closed without merging**
