### PR TITLE
upgrade jakarta.mail to 2.0.0 (rename javax.mail -> jakarta.mail)

### PR DESCRIPTION
**Pull request by gitmotte**
* upgrade jakarta.mail to 2.0.0 (rename javax.mail -> jakarta.mail)
* push version to 6.0.0 (breaking change)

### CODE REVIEW

**Comment by diegosalvi** [comment]
This is a very frightening update. Every project using subetha will have to cope with dependency upgrade.. and packages renames :(

**Comment by gitmotte** [comment]
there is a transformer plugin, which might be a good solution for the transition phase from javax to jakarta
``` 
<plugin>
        <groupId>org.eclipse.transformer</groupId>
        <artifactId>org.eclipse.transformer.maven</artifactId>
        <version>0.2.0</version>
        <executions>
          <execution>
            <id>jakarta-ee</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <classifier>jakarta</classifier>
            </configuration>
          </execution>
        </executions>
</plugin>
```
i'm not that happy with it, because afaik there is no depencency-check against the new api-version, but the new API should be binary compatible with the previous version.

**Comment by davidmoten** [comment]
I've got no objection to the breaking change to jakarta.mail. Updating package names in a few classes is not a big deal for me. Can you be more specific @diegosalvi about the problems this causes for you?

**Comment by gitmotte** [comment]
> I've got no objection to the breaking change to jakarta.mail. Updating package names in a few classes is not a big deal for me. Can you be more specific @diegosalvi about the problems this causes for you?

@diegosalvi  is right that this is a breaking change for dependent projects. 
i mentioned this at the beginning and that is why i increased the version number to 6.0.0.

the solution would be to publish both versions using the transformer plugin. btw. there is a invert - option (don't know exactly how it works, but it looks like transformation jakarta -> javax. testing it with invert option true did not work for me)

**Comment by davidmoten** [comment]
> @diegosalvi is right that this is a breaking change for dependent projects.
i mentioned this at the beginning and that is why i increased the version number to 6.0.0.

Yes indeed, but the breaking change is not difficult to adapt to as far as I can see. I'm in favour of migrating to jakarta.mail myself without transformer plugin but I'll wait for @diegosalvi to argue his case.

**Comment by diegosalvi** [comment]
@davidmoten Sooner or later this change must be done (... before that jackarta mail drifts too much from javamail).
Projects that embed subethamail and then have javamail object in his public api will have to keep both implementations and in some cases cope with conversion from and to javamail and jackarta.

Could be a good thing to keep alive for some time a 5.2 branch running for some time at least for bugfixes

**Comment by davidmoten** [comment]
> Could be a good thing to keep alive for some time a 5.2 branch running for some time at least for bugfixes.

Fine by me.

**Comment by middagj** [comment]
I am now facing the problem that subethasmtp is still on 1.x, but we are using other libraries that did upgrade to Jakarta 2.x

I think a bump in major to warn users is probably the best, next to keeping 5.x around for a while.

**Comment by davidmoten** [comment]
Excuse the delay, I'll get on to this shortly.

**Comment by davidmoten** [comment]
This has been merged and the jakarta.mail version 6.0.0 is now on Maven Central

**Pull request merged**
